services:
  web:
    image: prompt-library:latest
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynet

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env

    ports:
      - "6433:5432" # host_port:docker_port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prompt_user -d prompt_library"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynet
volumes:
  postgres_data:

networks:
  mynet:
    external: true